#!/bin/sh

if [[ -z "$SWAYSOCK" ]]; then
	echo "SWAYSOCK not set" > /dev/stderr
	exit 1
fi


PROCESSED_WALLPAPERS_DIR=$HOME/.local/processed-wallpapers
mkdir -p $PROCESSED_WALLPAPERS_DIR
IMAGE_HOME=/home/user


# INTERACTION=-d
INTERACTION=-it
# --privileged

# -u $(id -u):$(id -g) \

docker run \
    $INTERACTION \
    --rm \
    --privileged \
    -u $(id -u):$(id -g) \
    -e SWAYSOCK=/tmp/sway.sock \
    -v $SWAYSOCK:/tmp/sway.sock \
    -v ${HOME}/wallpapers:${IMAGE_HOME}/wallpapers \
    -v ${PROCESSED_WALLPAPERS_DIR}:${IMAGE_HOME}/.local/processed-wallpapers \
    -v ${HOME}/.config/wallpaper-directories:${IMAGE_HOME}/.config/wallpaper-directories \
    set-wallpaper:custom "$@"

    # --entrypoint /bin/sh \
    #     -c 'ls -al /tmp'
